[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "thinX"
version = "0.1.0"
description = "A package for experimenting with different distribution compression and XAI methods"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["thinX*"]